import { useState } from 'react'
import { StyleSheet, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'
import { Screen } from '../src/components/Screen'
import { PressableScale } from '../src/components/PressableScale'
import { colors, radii, spacing, type } from '../src/theme/tokens'

export default function PayInvoiceEntry() {
  const router=useRouter();const [reference,setReference]=useState('');const [email,setEmail]=useState('');const [error,setError]=useState('')
  const proceed=()=>{const ref=reference.trim();const mail=email.trim().toLowerCase();if(!ref){setError('Enter the invoice or project reference issued by 11-11 Tech.');return}if(!mail||!mail.includes('@')){setError('Enter the billing email attached to the engagement.');return}setError('');router.push({pathname:'/client',params:{reference:ref,email:mail}})}
  return <Screen contentStyle={styles.screen}><View style={styles.header}><View><Text style={styles.brand}>11·11 TECH</Text><Text style={styles.eyebrow}>SECURE BILLING · NATIVE</Text></View><PressableScale accessibilityLabel="Go back" onPress={()=>router.back()} style={styles.close}><Text style={styles.closeText}>×</Text></PressableScale></View><View style={styles.heroBlock}><Text style={styles.hero}>PAY AN INVOICE OR PROJECT BALANCE.</Text><Text style={styles.body}>A reference never exposes financial information by itself. We verify the billing email, open your secure workspace, require the applicable agreement and then hand card entry to Stripe.</Text></View><View style={styles.steps}>{['IDENTIFY · reference + billing email','REVIEW · exact invoice, balance and terms','AGREE · immutable issued documents','PAY · Stripe-hosted secure checkout','KEEP · invoice, receipt and agreement vault'].map((item,index)=><View key={item} style={styles.step}><Text style={styles.stepNo}>{String(index+1).padStart(2,'0')}</Text><Text style={styles.stepText}>{item}</Text></View>)}</View><View style={styles.form}>{error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}<Text style={styles.label}>INVOICE OR PROJECT REFERENCE</Text><TextInput value={reference} onChangeText={setReference} autoCapitalize="characters" autoCorrect={false} placeholder="11T-INV-2026-00042" placeholderTextColor={colors.textMutedDark} style={styles.input}/><Text style={styles.label}>BILLING EMAIL</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" placeholder="accounts@organisation.com" placeholderTextColor={colors.textMutedDark} style={styles.input}/><PressableScale accessibilityLabel="Continue securely" onPress={proceed} style={styles.primary}><Text style={styles.primaryText}>CONTINUE SECURELY →</Text></PressableScale><Text style={styles.note}>No card information is collected in this screen or stored by 11-11 Tech.</Text></View></Screen>
}

const styles=StyleSheet.create({screen:{gap:spacing.xxl},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{color:colors.textOnDark,fontFamily:type.display,fontSize:24},eyebrow:{color:colors.orange,fontFamily:type.mono,fontSize:10,letterSpacing:1.2},close:{width:48,height:48,borderWidth:StyleSheet.hairlineWidth,borderColor:colors.ruleDark,alignItems:'center',justifyContent:'center'},closeText:{color:colors.textOnDark,fontSize:28},heroBlock:{gap:spacing.md},hero:{color:colors.textOnDark,fontFamily:type.display,fontSize:43,lineHeight:44,letterSpacing:-1.1},body:{color:colors.textMutedDark,fontFamily:type.body,fontSize:15,lineHeight:23},steps:{borderTopWidth:StyleSheet.hairlineWidth,borderColor:colors.ruleDark},step:{minHeight:52,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:colors.ruleDark,flexDirection:'row',alignItems:'center',gap:spacing.md},stepNo:{color:colors.orange,fontFamily:type.mono,fontSize:10},stepText:{flex:1,color:colors.textOnDark,fontFamily:type.mono,fontSize:10,letterSpacing:.4},form:{gap:spacing.sm,backgroundColor:colors.inkRaised,padding:spacing.lg,borderRadius:radii.sm},label:{color:colors.textMutedDark,fontFamily:type.mono,fontSize:10,letterSpacing:1,marginTop:spacing.sm},input:{minHeight:54,borderWidth:StyleSheet.hairlineWidth,borderColor:colors.ruleDark,borderRadius:radii.sm,paddingHorizontal:spacing.md,color:colors.textOnDark,fontFamily:type.body,fontSize:16},primary:{minHeight:54,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center',borderRadius:radii.sm,marginTop:spacing.sm},primaryText:{color:colors.ink,fontFamily:type.mono,fontSize:11,fontWeight:'700',letterSpacing:.7},note:{color:colors.textMutedDark,fontFamily:type.body,fontSize:12,lineHeight:18},error:{borderLeftWidth:3,borderLeftColor:colors.danger,padding:spacing.sm,backgroundColor:colors.inkSoft},errorText:{color:'#FFD0D0',fontFamily:type.body,fontSize:13}})
