import { useState } from 'react'
import { StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native'
import { useRouter } from 'expo-router'
import { Screen } from '../src/components/Screen'
import { AppHeader } from '../src/components/AppHeader'
import { PressableScale } from '../src/components/PressableScale'
import { radii, spacing, type } from '../src/theme/tokens'
import { useTheme } from '../src/theme/ThemeProvider'

export default function PayInvoiceEntry() {
  const router = useRouter(); const { theme } = useTheme(); const { width } = useWindowDimensions()
  const [reference,setReference]=useState('');const [email,setEmail]=useState('');const [error,setError]=useState('')
  const proceed=()=>{const ref=reference.trim();const mail=email.trim().toLowerCase();if(!ref){setError('Enter the invoice or project reference issued by 11-11 Tech.');return}if(!mail||!mail.includes('@')){setError('Enter the billing email attached to the engagement.');return}setError('');router.push({pathname:'/client',params:{reference:ref,email:mail}})}
  return <Screen contentStyle={styles.screen}><AppHeader back title="Secure billing"/><View style={styles.heroBlock}><Text accessibilityRole="header" style={[styles.hero,{color:theme.text,fontSize:width<360?36:43,lineHeight:width<360?38:44}]}>PAY AN INVOICE OR PROJECT BALANCE.</Text><Text style={[styles.body,{color:theme.muted}]}>A reference never exposes financial information by itself. We verify the billing email, open your secure workspace, require the applicable agreement and then hand card entry to Stripe.</Text></View><View style={[styles.steps,{borderColor:theme.rule}]}>{['IDENTIFY · reference + billing email','REVIEW · exact invoice, balance and terms','AGREE · immutable issued documents','PAY · Stripe-hosted secure checkout','KEEP · invoice, receipt and agreement vault'].map((item,index)=><View key={item} style={[styles.step,{borderColor:theme.rule}]}><Text style={[styles.stepNo,{color:theme.accent}]}>{String(index+1).padStart(2,'0')}</Text><Text style={[styles.stepText,{color:theme.text}]}>{item}</Text></View>)}</View><View style={[styles.form,{backgroundColor:theme.surface,borderColor:theme.rule}]}>{error?<View accessibilityRole="alert" style={[styles.error,{borderLeftColor:theme.danger,backgroundColor:theme.elevated}]}><Text style={[styles.errorText,{color:theme.danger}]}>{error}</Text></View>:null}<Text style={[styles.label,{color:theme.muted}]}>INVOICE OR PROJECT REFERENCE</Text><TextInput value={reference} onChangeText={setReference} autoCapitalize="characters" autoCorrect={false} returnKeyType="next" placeholder="11T-INV-2026-00042" placeholderTextColor={theme.muted} style={[styles.input,{borderColor:theme.inputBorder,backgroundColor:theme.input,color:theme.text}]}/><Text style={[styles.label,{color:theme.muted}]}>BILLING EMAIL</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" autoComplete="email" returnKeyType="go" onSubmitEditing={proceed} placeholder="accounts@organisation.com" placeholderTextColor={theme.muted} style={[styles.input,{borderColor:theme.inputBorder,backgroundColor:theme.input,color:theme.text}]}/><PressableScale accessibilityLabel="Continue securely" accessibilityHint="Opens the secure client workspace after validating the reference and billing email" onPress={proceed} style={[styles.primary,{backgroundColor:theme.accent}]}><Text style={[styles.primaryText,{color:theme.accentOn}]}>CONTINUE SECURELY →</Text></PressableScale><Text style={[styles.note,{color:theme.muted}]}>No card information is collected in this screen or stored by 11-11 Tech.</Text></View></Screen>
}

const styles=StyleSheet.create({screen:{gap:spacing.xxl},heroBlock:{gap:spacing.md},hero:{fontFamily:type.display,letterSpacing:-1.1},body:{fontFamily:type.body,fontSize:15,lineHeight:23},steps:{borderTopWidth:StyleSheet.hairlineWidth},step:{minHeight:52,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center',gap:spacing.md},stepNo:{fontFamily:type.mono,fontSize:10},stepText:{flex:1,fontFamily:type.mono,fontSize:10,letterSpacing:.4},form:{gap:spacing.sm,padding:spacing.lg,borderRadius:radii.sm,borderWidth:StyleSheet.hairlineWidth},label:{fontFamily:type.mono,fontSize:10,letterSpacing:1,marginTop:spacing.sm},input:{minHeight:54,borderWidth:StyleSheet.hairlineWidth,borderRadius:radii.sm,paddingHorizontal:spacing.md,fontFamily:type.body,fontSize:16},primary:{minHeight:54,alignItems:'center',justifyContent:'center',borderRadius:radii.sm,marginTop:spacing.sm},primaryText:{fontFamily:type.mono,fontSize:11,fontWeight:'700',letterSpacing:.7},note:{fontFamily:type.body,fontSize:12,lineHeight:18},error:{borderLeftWidth:3,padding:spacing.sm},errorText:{fontFamily:type.body,fontSize:13}})
