import { StyleSheet, Text, View } from 'react-native'
import { useRouter } from 'expo-router'
import { Screen } from '../src/components/Screen'
import { AppHeader } from '../src/components/AppHeader'
import { ActionButton } from '../src/components/ActionButton'
import { CinematicHero, Disclosure, Pill } from '../src/components/Editorial'
import { capabilities, pricingBands } from '../../shared/portfolio'
import { media } from '../../shared/media'
import { useTheme } from '../src/theme/ThemeProvider'
import { type } from '../src/theme/tokens'

export default function Pricing(){const router=useRouter();const{theme}=useTheme();return <Screen><AppHeader back title="Pricing"/><CinematicHero image={media.abstractEditorial} eyebrow="Scope · complexity · delivery · assurance" title="Know the range before the proposal." body="Most defined engagements begin between US$2,000 and US$10,000. Larger or ongoing work is custom-scoped."/><View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>PUBLIC PLANNING BANDS</Text>{pricingBands.map(b=><View key={b.label} style={[styles.band,{backgroundColor:theme.surface,borderColor:theme.rule}]}><Text style={[styles.bandLabel,{color:theme.muted}]}>{b.label.toUpperCase()}</Text><Text style={[styles.bandValue,{color:theme.text}]}>{b.range}</Text><Text style={[styles.body,{color:theme.muted}]}>{b.detail}</Text></View>)}</View><View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>BY CAPABILITY</Text>{capabilities.map(cap=><Disclosure key={cap.id} title={`${cap.title} · ${cap.typicalRange}`} summary={cap.proposition}><Text style={[styles.body,{color:theme.muted}]}>{cap.proposition}</Text>{cap.services.map(s=><View key={s.name} style={[styles.service,{borderColor:theme.rule}]}><Text style={[styles.serviceName,{color:theme.text}]}>{s.name}</Text><Text style={[styles.servicePrice,{color:theme.accent}]}>{s.price}</Text></View>)}<ActionButton label="Estimate this work" variant="outline" onPress={()=>router.push({pathname:'/start',params:{capability:cap.id}})}/></Disclosure>)}</View><View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>COMMERCIAL MODELS</Text><View style={styles.pills}>{['Fixed scope','Discovery + implementation','Monthly partnership','Recruitment / RPO','Enterprise custom'].map(x=><Pill key={x}>{x}</Pill>)}</View><Text style={[styles.body,{color:theme.muted}]}>Third-party cloud, model, API, software-license or media fees are normally separate unless explicitly included. Material client-specific compliance, certification, infrastructure or legal requirements may change scope and price. Public ranges are planning guidance, not binding quotations.</Text><ActionButton label="Start a project" onPress={()=>router.push('/start')}/></View></Screen>}
const styles=StyleSheet.create({section:{gap:14,marginTop:44},kicker:{fontFamily:type.mono,fontSize:9,letterSpacing:1.3},band:{padding:18,borderWidth:StyleSheet.hairlineWidth,gap:8},bandLabel:{fontFamily:type.mono,fontSize:9,letterSpacing:1},bandValue:{fontFamily:type.display,fontSize:30},body:{fontFamily:type.body,fontSize:15,lineHeight:22},service:{borderTopWidth:StyleSheet.hairlineWidth,paddingVertical:11,flexDirection:'row',gap:12,justifyContent:'space-between'},serviceName:{fontFamily:type.body,fontSize:14,flex:1},servicePrice:{fontFamily:type.mono,fontSize:11},pills:{flexDirection:'row',flexWrap:'wrap',gap:8}})
