import { PageHero } from '../components/PageHero'
import { Link } from '../components/Link'
import { accelerators, capabilities } from '../data/portfolio'
import { media } from '../lib/media'

const ecosystem = ['React','TypeScript','Node','PostgreSQL','Supabase','Vercel','Cloudflare','GitHub','Playwright','OpenAI models','Anthropic models','Google AI','Higgsfield','ElevenLabs','Stripe']

export function About(){return <>
  <PageHero index="09" kicker="Company" title={<>An IT services company built around <span className="soft">design, systems, AI and people.</span></>}>11-11 Tech helps organizations improve digital experiences, build and modernize business systems, implement AI and automation, engineer software and data infrastructure, transform technology operations and strengthen technical teams.</PageHero>

  <section className="editorial-media reveal"><img src={media.crossCulture} alt="Japanese and African technology professionals collaborating in a modern studio"/><div className="editorial-media-shade"/><div className="wrap editorial-media-copy"><span>11-11 TECH / CROSS-MARKET TECHNOLOGY</span><h2>Technology services shaped by different people, markets and operating realities.</h2></div></section>

  <section className="section"><div className="wrap company-definition-grid reveal"><div><div className="kicker">What we are</div><h2>Technology services for organizations that need more than a website.</h2></div><div><p><strong>11-11 Tech is a multidisciplinary IT services and technology implementation company.</strong> We combine UI/UX and front-end engineering, CRM and enterprise systems, AI implementation, software/data/cloud engineering, digital transformation, technology recruitment and engineering assurance.</p><p>A client can come to us with a business problem rather than a technical specification. We help define what should change, design the experience and system, implement the technology, test it, launch it and support improvement after launch.</p><div className="inline-actions"><Link className="btn primary" to="/capabilities">Explore IT services ↗</Link><Link className="btn ghost" to="/industries">See industries</Link></div></div></div></section>

  <section className="section"><div className="wrap"><div className="principles reveal"><div className="principle"><span>01</span><h3>Make the service understandable.</h3><p>Clients should know what they are buying, what changes, what it may cost and what the next step is.</p></div><div className="principle"><span>02</span><h3>Design for the real environment.</h3><p>Markets have different users, infrastructure, trust patterns, budgets and operating realities.</p></div><div className="principle"><span>03</span><h3>Finish the operational loop.</h3><p>Testing, documentation, governance, handover, support and improvement are part of technology delivery.</p></div></div></div></section>

  <section className="section alt-section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Business architecture</div><h2>Multiple ways to engage, one technology partner.</h2></div><p>The company is designed to earn through defined projects, advisory, recurring improvement, talent services and reusable technology capability—not one-off website builds alone.</p></div><div className="commercial-model-grid"><article><span>PROJECTS</span><h3>Design & implementation</h3><p>UI/UX, CRM, AI, software, integrations, data, modernization and assurance.</p></article><article><span>CONSULTING</span><h3>Discovery & advisory</h3><p>Audits, architecture, transformation roadmaps and technology leadership.</p></article><article><span>RECURRING</span><h3>Operate & improve</h3><p>Support, product optimization, AI monitoring and ongoing technical partnership.</p></article><article><span>TALENT</span><h3>Recruitment & RPO</h3><p>Technical search, embedded recruitment, screening, talent mapping and team building.</p></article><article><span>IP / PRODUCTS</span><h3>Reusable capability</h3><p>Technology portfolio, accelerators and future product or platform revenue.</p></article></div></div></section>

  <section className="section"><div className="wrap"><div className="founder founder-media reveal"><div><div className="founder-mark">11 / 11</div><div className="kicker">Founder</div><h2>Shadreck Kudzanai Musarurwa</h2><p>Tokyo-based product and technology professional with experience spanning UI/front-end product work, software and application development, product strategy, technical documentation, recruitment and talent acquisition, training and international business.</p></div><div className="founder-facts"><span>MBA · Shizenkan Business School</span><span>BA Liberal Arts · Tokyo Christian University</span><span>B.Tech International Marketing · CUT</span><span>HTML5 Professional Level 1</span><span>UI/UX & front-end product work</span><span>Technical recruitment & talent operations</span><span>Product strategy & application development</span><span>Technical documentation & certification</span></div></div></div></section>

  <section className="section editorial-light cross-market-v22"><div className="wrap">
    <div className="editorial-heading light-heading reveal"><div><span className="kicker">Cross-market perspective</span><h2>Different contexts. One standard of craft.</h2></div><p>Our visual and product thinking is informed by Japan, Africa and distributed global work—not by assuming every organization operates the same way.</p></div>
    <div className="cross-market-grid-v22 reveal">
      <figure><img src={media.tokyoBusiness} alt="Tokyo technology and business environment" loading="lazy"/><figcaption><strong>Tokyo</strong><span>Precision · product discipline · dense digital infrastructure</span></figcaption></figure>
      <figure><img src={media.harareBusiness} alt="Harare technology and business environment" loading="lazy"/><figcaption><strong>Harare</strong><span>Adaptability · emerging-market realities · practical systems</span></figcaption></figure>
    </div>
  </div></section>

  <section className="full-bleed-media compact-media reveal"><img src={media.globalBridge} alt="Tokyo and Southern African urban environments connected through technology" loading="lazy"/><div className="full-bleed-shade"/><div className="wrap full-bleed-copy"><div className="kicker">Operating position</div><h2>Tokyo-built. Africa-aware. Global by design.</h2><p>Japan is the operating base. The company is shaped for cross-market work, different infrastructure realities and globally distributed teams.</p><div className="route-dots"><span>Japan</span><span>Africa</span><span>Europe</span><span>Americas</span><span>Distributed teams</span></div></div></section>

  <section className="section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">IT service portfolio</div><h2>Seven practices that can combine into one engagement.</h2></div><Link className="text-link" to="/capabilities">Explore all services ↗</Link></div><div className="mini-company-capabilities">{capabilities.map((capability) => <Link key={capability.id} to={`/capabilities/${capability.id}`}><span>{capability.index}</span><strong>{capability.shortTitle}</strong></Link>)}</div></div></section>

  <section className="section alt-section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Reusable methods</div><h2>11-11 accelerators.</h2></div><p>Named delivery frameworks make expertise repeatable without pretending every client needs the same implementation.</p></div><div className="accelerator-grid">{accelerators.map((accelerator) => <article className="reveal" key={accelerator.name}><span>11-11 ACCELERATOR</span><h3>{accelerator.name}</h3><p>{accelerator.description}</p></article>)}</div></div></section>

  <section className="section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Technology ecosystem</div><h2>Tools we work with, selected to fit the problem.</h2></div><p>Vendor and model choice follows the client problem, architecture, governance and cost profile. These are technologies we work with, not fabricated partnership claims.</p></div><div className="tech-orbit reveal" aria-label="Technology ecosystem">{ecosystem.map((item) => <span key={item}>{item}</span>)}</div></div></section>

  <section className="section compact"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Professional environments</div><h2>Experience beyond one company label.</h2></div><p>Technology delivery, talent and training across international teams.</p></div><div className="experience-ribbon reveal" aria-label="Selected professional environments"><span>Oiko Techno Japan</span><span>Infosys</span><span>HCL</span><span>Iron Systems</span><span>IRTAMI</span><span>Smart Solutions</span><span>Sharp Brains</span></div><p className="experience-note reveal">Professional experience and teams supported; not presented as a fabricated 11-11 Tech client roster.</p></div></section>

  <section className="section assurance-section"><div className="wrap investment-callout reveal"><div><div className="kicker">Investors & strategic partners</div><h2>Interested in the company thesis, technology portfolio or strategic collaboration?</h2><p>Public pages explain the operating model and portfolio without inventing revenue, traction or valuation claims. Deeper information can be shared privately with serious counterparties.</p></div><Link className="btn primary" to="/contact?outcome=unknown">Start a strategic conversation ↗</Link></div></section>
</>}
