import { PageHero } from '../components/PageHero'
import { Link } from '../components/Link'
import { accelerators, capabilities } from '../data/portfolio'
import { media } from '../lib/media'

const ecosystem = ['React','TypeScript','Node','PostgreSQL','Supabase','Vercel','Cloudflare','GitHub','Playwright','OpenAI models','Anthropic models','Google AI','Higgsfield','ElevenLabs','Stripe']

export function About(){return <>
  <PageHero index="09" kicker="Company" title={<>Built between <span className="soft">systems and people.</span></>}>11-11 Tech is a Tokyo-based technology company spanning product experience, enterprise systems, AI implementation, software, transformation, talent and engineering assurance.</PageHero>

  <section className="editorial-media reveal"><img src={media.builders} alt="Technology builders working with spatial prototypes in a modern Tokyo studio"/><div className="editorial-media-shade"/><div className="wrap editorial-media-copy"><span>TOKYO / EXPERIENCE / SYSTEMS / AI</span><h2>Technology is strongest when it understands where it lands.</h2></div></section>

  <section className="section"><div className="wrap"><div className="principles reveal"><div className="principle"><span>01</span><h3>Say what is real.</h3><p>Prototype, pilot, active build and production are different states.</p></div><div className="principle"><span>02</span><h3>Design for the place.</h3><p>Markets have different trust, infrastructure and operating realities.</p></div><div className="principle"><span>03</span><h3>Finish the loop.</h3><p>Operations, evidence, documentation, adoption and failure states are technology work.</p></div></div></div></section>

  <section className="section alt-section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Business architecture</div><h2>Services today. Repeatable IP and product value over time.</h2></div><p>The company is designed to earn through multiple commercial models rather than depend on one-off website builds.</p></div><div className="commercial-model-grid"><article><span>PROJECTS</span><h3>Design & implementation</h3><p>UI/UX, systems, AI, software, modernization and assurance.</p></article><article><span>CONSULTING</span><h3>Discovery & advisory</h3><p>Audits, architecture, transformation and technology leadership.</p></article><article><span>RECURRING</span><h3>Managed improvement</h3><p>Support, product optimization, AI monitoring and ongoing technical partnership.</p></article><article><span>TALENT</span><h3>Recruitment & RPO</h3><p>Technical search, embedded recruitment, assessment and team building.</p></article><article><span>IP / PRODUCTS</span><h3>Reusable capability</h3><p>Technology portfolio, accelerators and future product or platform revenue.</p></article></div></div></section>

  <section className="section"><div className="wrap"><div className="founder founder-media reveal"><div><div className="founder-mark">11 / 11</div><div className="kicker">Founder</div><h2>Shadreck Kudzanai Musarurwa</h2><p>Product and technology professional based in the Tokyo area, with more than a decade in Japan and experience spanning software, strategy, leadership, talent, training and international marketing.</p></div><div className="founder-facts"><span>MBA · Shizenkan Business School</span><span>BA Liberal Arts · Tokyo Christian University</span><span>B.Tech International Marketing · CUT</span><span>HTML5 Professional Level 1</span><span>UI/UX & front-end product work</span><span>Technical recruitment & talent operations</span><span>Product strategy & application development</span><span>Technical documentation & certification</span></div></div></div></section>

  <section className="full-bleed-media compact-media reveal"><img src={media.global} alt="Nighttime global infrastructure connected by blue routes" loading="lazy"/><div className="full-bleed-shade"/><div className="wrap full-bleed-copy"><div className="kicker">Trajectory</div><h2>Japan as the operating base. Global problems as the canvas.</h2><div className="route-dots"><span>Japan</span><span>Africa</span><span>Europe</span><span>Americas</span><span>Distributed teams</span></div></div></section>

  <section className="section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Capability system</div><h2>Seven practices that can combine into one engagement.</h2></div><Link className="text-link" to="/capabilities">Explore capabilities ↗</Link></div><div className="mini-company-capabilities">{capabilities.map((capability) => <Link key={capability.id} to={`/capabilities/${capability.id}`}><span>{capability.index}</span><strong>{capability.shortTitle}</strong></Link>)}</div></div></section>

  <section className="section alt-section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Reusable methods</div><h2>11-11 accelerators.</h2></div><p>Named delivery frameworks make expertise repeatable without pretending every client needs the same implementation.</p></div><div className="accelerator-grid">{accelerators.map((accelerator) => <article className="reveal" key={accelerator.name}><span>11-11 ACCELERATOR</span><h3>{accelerator.name}</h3><p>{accelerator.description}</p></article>)}</div></div></section>

  <section className="section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Technology ecosystem</div><h2>Tools we work with, not fabricated partnership claims.</h2></div><p>Vendor and model choice follows the client problem, architecture, governance and cost profile.</p></div><div className="tech-orbit reveal" aria-label="Technology ecosystem">{ecosystem.map((item) => <span key={item}>{item}</span>)}</div></div></section>

  <section className="section compact"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Professional environments</div><h2>Experience beyond one company label.</h2></div><p>Technology delivery, talent and training across international teams.</p></div><div className="experience-ribbon reveal" aria-label="Selected professional environments"><span>Oiko Techno Japan</span><span>Infosys</span><span>HCL</span><span>Iron Systems</span><span>IRTAMI</span><span>Smart Solutions</span><span>Sharp Brains</span></div><p className="experience-note reveal">Professional experience and teams supported; not presented as a fabricated 11-11 Tech client roster.</p></div></section>

  <section className="section assurance-section"><div className="wrap investment-callout reveal"><div><div className="kicker">Investors & strategic partners</div><h2>Interested in the company thesis, technology portfolio or strategic collaboration?</h2><p>Public pages explain the operating model and portfolio without inventing revenue, traction or valuation claims. Deeper information can be shared privately with serious counterparties.</p></div><Link className="btn primary" to="/contact?outcome=unknown">Start a strategic conversation ↗</Link></div></section>
</>}
