import { PageHero } from '../components/PageHero'

export function About(){return <>
  <PageHero index="03" kicker="About" title={<>Born from <span className="soft">building.</span></>}>11-11 Tech brings together product strategy, software engineering, documentation, quality assurance and cross-cultural operating experience from Tokyo into one studio.</PageHero>
  <section className="section"><div className="wrap"><div className="principles reveal"><div className="principle"><span>01</span><h3>Say what is real.</h3><p>Prototype is not production. A screen is not a workflow. A green build is not physical-device UAT. We label states accurately.</p></div><div className="principle"><span>02</span><h3>Design for the place.</h3><p>Zimbabwe, Zambia, Japan and diaspora markets have different infrastructure, trust, payment and user-context realities. Product design should know that.</p></div><div className="principle"><span>03</span><h3>Finish the loop.</h3><p>Good software includes operations, documentation, failure states, authority, evidence, testing and the path after launch.</p></div></div></div></section>
  <section className="section"><div className="wrap"><div className="founder reveal"><div><div className="founder-mark">11 / 11</div><div className="kicker">Founder</div><h2>Shadreck Kudzanai Musarurwa</h2><p>Tokyo-based product and technology professional with more than a decade in Japan and a multidisciplinary background spanning software, product strategy, leadership, talent, training and international marketing.</p></div><div><ul><li>MBA — Shizenkan Business School, Tokyo</li><li>BA Liberal Arts — Tokyo Christian University</li><li>B.Tech International Marketing — Chinhoyi University of Technology</li><li>HTML5 Professional Level 1</li><li>Product strategy & application development</li><li>Technical documentation & certification</li></ul></div></div></div></section>
  <section className="section compact"><div className="wrap"><div className="section-head reveal"><div><div className="kicker">Professional environments</div><h2>Experience beyond a single studio label.</h2></div><p>Before and alongside 11-11 Tech, the founder’s work has crossed technology delivery, talent, training and international operating environments.</p></div><div className="experience-ribbon reveal" aria-label="Selected professional environments"><span>Oiko Techno Japan</span><span>Infosys</span><span>HCL</span><span>Iron Systems</span><span>IRTAMI</span><span>Smart Solutions</span><span>Sharp Brains</span></div><p className="experience-note reveal">These names describe professional experience and teams supported; they are not presented as a fabricated 11-11 Tech client list.</p></div></section>
  <section className="section"><div className="wrap"><div className="section-head reveal"><div><div className="kicker">Trajectory</div><h2>From cross-disciplinary work to a technology studio.</h2></div><p>The company is the consolidation of years spent moving between people, systems, markets, documentation and software rather than a sudden rebrand around one technology trend.</p></div><div className="timeline reveal"><div className="time-row"><strong>2006–2010</strong><div><h3>International marketing foundation</h3><p>Commercial thinking, markets and customer context.</p></div></div><div className="time-row"><strong>2015–2019</strong><div><h3>Liberal arts, linguistics and Japan</h3><p>Communication, culture, research and a long-term operating base in Tokyo.</p></div></div><div className="time-row"><strong>2019–2021</strong><div><h3>MBA: leadership & societal innovation</h3><p>Systems thinking, organizational leadership and technology as part of wider social infrastructure.</p></div></div><div className="time-row"><strong>2025–2026</strong><div><h3>Portfolio consolidation</h3><p>Marketplaces, trust products, education tools, media systems and operating-system work converge into a repeatable delivery practice.</p></div></div><div className="time-row"><strong>11-11</strong><div><h3>11-11 Tech</h3><p>A Tokyo-based studio serving global product work with particular depth in African market problems.</p></div></div></div></div></section>
</>}
