import { Link, hrefFor } from '../components/Link'

export function Home() {
  return <>
    <section className="hero"><div className="wrap hero-grid">
      <div className="reveal"><span className="eyebrow">Tokyo-built · globally useful</span><h1>Digital systems with <span className="soft">real-world gravity.</span></h1><p className="hero-copy">11-11 Tech is a product engineering and documentation studio turning complex operations into clear, trustworthy software—across mobility, media, health, community systems, education and marketplaces.</p><div className="hero-actions"><Link className="btn primary" to="/work">Explore the work ↗</Link><Link className="btn ghost" to="/contact">Start a project</Link></div><div className="paired-lines" aria-hidden="true"><span/><span/><span/><span/></div><p className="muted">Mission: <strong>turn difficult real-world problems into digital products people can trust, use and grow with.</strong></p></div>
      <div className="hero-art reveal"><img src={hrefFor('/assets/scenes/hero-network.svg')} alt="Abstract network connecting Tokyo with Africa, Europe and the Americas"/><div className="stamp"><small>11-11 principle</small><strong>11:11</strong><small>Build here. Serve everywhere.</small></div></div>
    </div></section>
    <section className="band"><div className="wrap band-inner"><span className="band-label">Working across</span><div className="marquee"><span>Product engineering</span><i>◆</i><span>Platform recovery</span><i>◆</i><span>Mobile + web</span><i>◆</i><span>AI-enabled workflows</span><i>◆</i><span>Technical documentation</span><i>◆</i><span>QA & certification</span></div></div></section>
    <section className="section"><div className="wrap"><div className="section-head reveal"><div><div className="kicker">Selected work</div><h2>Products built around trust, not theatre.</h2></div><p>We work where software touches actual life: buying a vehicle, booking a rehearsal room, running a newsroom, coordinating a community, teaching a classroom or turning a service marketplace into something people can verify.</p></div>
      <Feature image="carup.svg" eyebrow="CarUp · Zimbabwe" title="A marketplace where a vehicle has a history—not just a listing." text="CarUp combines marketplace discovery with a Vehicle Digital Passport, evidence, seller workflows, trust signals and an intelligence layer designed around the realities of Zimbabwe and its diaspora." tags={['Mobility','Trust systems','Marketplace','Evidence']} />
      <Feature reverse image="sessions.svg" eyebrow="Sessions · Zimbabwe" title="Rehearsal infrastructure, treated like infrastructure." text="Sessions turns studio discovery into a controlled marketplace: sourced venue registry, provider ownership, room inventory, booking integrity, finance boundaries and operations authority." tags={['Music','Bookings','Provider operations']} />
      <Feature image="healthtimes.svg" eyebrow="HealthTimes 2.1 · Zimbabwe" title="Editorial modernization that respects the business behind the publication." text="Premium reading, native-feeling mobile UX, newsroom roles, advertising, subscriber journeys, PWA readiness and an intelligence layer—designed as modernization, not a cosmetic redesign." tags={['Health media','Newsroom','PWA','Premium']} />
    </div></section>
    <section className="section compact"><div className="wrap"><div className="metric-rail reveal"><Metric big="22" text="named product builds, prototypes and operating-system experiments represented in the current studio archive"/><Metric big="4" text="primary service regions: Japan, Africa, Europe and the Americas"/><Metric big="1→N" text="one product truth, many usable surfaces—web, mobile, admin, operations and documentation"/><Metric big="11:11" text="our reminder that timing matters, but operating discipline matters more"/></div></div></section>
    <section className="section"><div className="wrap"><div className="section-head reveal"><div><div className="kicker">What we do</div><h2>Strategy, software and system truth in the same room.</h2></div><p>11-11 Tech is deliberately multidisciplinary. We can enter at the idea stage, architecture stage, or when a product is already moving but no longer knows what is true.</p></div><div className="service-lines reveal">
      {services.map((service, index) => <div className="service-row" key={service[0]}><span className="num">{String(index+1).padStart(2,'0')} / 07</span><h3>{service[0]}</h3><p>{service[1]}</p></div>)}
    </div></div></section>
    <section className="section"><div className="wrap"><div className="global reveal"><img src={hrefFor('/assets/scenes/hero-network.svg')} alt="Global network from Tokyo"/><div className="global-copy"><div className="kicker">Tokyo → world</div><h3>Local context. Global engineering standards.</h3><p>Based in Tokyo, 11-11 Tech builds with specific markets in mind—particularly African products that need world-class execution without losing local reality.</p><div className="route-dots"><span>Tokyo / Japan</span><span>Zimbabwe</span><span>Zambia</span><span>Europe</span><span>Americas</span></div></div></div></div></section>
    <section className="section"><div className="wrap"><div className="manifesto reveal"><blockquote>“Build what matters. <span className="accent">Prove what works.</span> Leave the system clearer than you found it.”</blockquote><div className="copy"><div className="kicker">Operating principle</div><p>We do not count a feature as real because a screen exists. We separate prototype from production, sample data from authoritative data, attractive UI from usable workflow, and confident language from evidence.</p><p>That discipline shows up in code, documentation, test gates and the way we describe what a product can—and cannot yet—do.</p></div></div></div></section>
  </>
}

function Feature({ image, eyebrow, title, text, tags, reverse=false }: { image:string; eyebrow:string; title:string; text:string; tags:string[]; reverse?:boolean }) {
  return <div className={`feature-split ${reverse ? 'reverse' : ''} reveal`}><div className="feature-media"><img src={hrefFor(`/assets/scenes/${image}`)} alt=""/></div><div className="feature-copy"><span className="eyebrow">{eyebrow}</span><h3>{title}</h3><p>{text}</p><div className="tags">{tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div><Link className="text-link" to="/work">See the portfolio</Link></div></div>
}
function Metric({big,text}:{big:string;text:string}) { return <div className="metric"><strong>{big}</strong><span>{text}</span></div> }
const services = [
  ['Product strategy & architecture','Product framing, user journeys, system boundaries, authority models, roadmaps and decision records.'],
  ['Web & app engineering','Responsive web, PWAs, marketplace experiences, dashboards and mobile-first product surfaces.'],
  ['Platform recovery & modernization','Reconcile fragmented code, clarify the source of truth, close hidden gaps and move a stalled build forward.'],
  ['AI-enabled product workflows','Structured AI features constrained by authoritative data, visible interpretation and product-safe boundaries.'],
  ['Technical documentation','BRDs, operating manuals, implementation plans, architecture notes, migration packs and client-review materials.'],
  ['QA, UAT & certification','Test strategy, Playwright/Vitest gates, evidence-led closure and launch-readiness thinking.'],
  ['Deployment systems','GitHub, CI/CD, Vercel, Cloudflare, Supabase, environment controls and production handoff.'],
]
