import type { ReactNode } from 'react'
import { PageHero } from '../components/PageHero'
export function Policies(){return <>
 <PageHero index="07" kicker="Public policies" title={<>Clear <span className="soft">expectations.</span></>}>A practical starting set of public policies for the GitHub Pages phase. These are operational drafts and should receive jurisdiction-specific legal review before high-risk or regulated production use.</PageHero>
 <section className="section"><div className="wrap policy-grid"><nav className="policy-nav" aria-label="Policy sections"><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#accessibility">Accessibility</a><a href="#ai">Responsible AI</a><a href="#security">Security</a><a href="#data">Data principles</a></nav><div>
  <Policy id="privacy" title="Privacy"><p>11-11 Tech aims to collect the minimum personal information necessary to communicate, deliver work and operate its public services. This first GitHub Pages release does not send inquiry form data to a database.</p><h3>What we may collect later</h3><p>Contact details, organization details, project requirements and technical logs may be processed once production services are connected. Collection will be disclosed at the point of use.</p><h3>International work</h3><p>Because the studio serves multiple regions, production systems must document where information is stored and which service providers process it.</p></Policy>
  <Policy id="terms" title="Website terms"><p>Public content is provided for general information about 11-11 Tech, its capabilities and product portfolio. Project descriptions distinguish active builds, prototypes and earlier work wherever practical.</p><p>Nothing on this website forms a project contract, service-level commitment or guarantee of product availability.</p></Policy>
  <Policy id="accessibility" title="Accessibility"><p>We design for keyboard access, visible focus, semantic structure, responsive layouts, reduced-motion preferences and readable contrast. Accessibility issues can be reported by email and are treated as product defects.</p></Policy>
  <Policy id="ai" title="Responsible AI"><p>AI systems are used as tools for design, engineering, documentation, content transformation and product assistance. They are not treated as automatic authority for facts, availability, pricing, identity, medical advice or other high-impact decisions.</p><h3>Human accountability</h3><p>People remain responsible for product decisions, published claims and production configuration.</p></Policy>
  <Policy id="security" title="Security & disclosure"><p>11-11 Tech uses least-privilege thinking, environment separation, reviewable changes and evidence-led testing. Please report suspected security issues privately rather than publishing exploit details against an active system.</p></Policy>
  <Policy id="data" title="Cookie & data principles"><p>This starting site does not require advertising cookies or a marketing tracker. Future analytics should be privacy-aware, proportionate, documented and consent-managed where required.</p><div className="policy-note">Legal notice: these policies are an operational starting point and are not a substitute for legal advice in Japan, Zimbabwe, Zambia, the EU, the United States or other jurisdictions.</div></Policy>
 </div></div></section>
 </>}
function Policy({id,title,children}:{id:string;title:string;children:ReactNode}){return <section className="policy-section" id={id}><h2>{title}</h2>{children}</section>}
