import type { ReactNode } from 'react'
import { PageHero } from '../components/PageHero'
import { Link } from '../components/Link'

export function Policies(){return <>
 <PageHero index="11" kicker="Public policies" title={<>Clear <span className="soft">expectations.</span></>}>Public operational principles for the website and early commercial relationship. Contracting documents for a real engagement are handled through the Trust Center and signed project terms.</PageHero>
 <section className="section"><div className="wrap policy-grid"><nav className="policy-nav" aria-label="Policy sections"><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#accessibility">Accessibility</a><a href="#ai">Responsible AI</a><a href="#security">Security</a><a href="#data">Data principles</a><Link to="/trust">Trust Center ↗</Link></nav><div>
  <Policy id="privacy" title="Privacy"><p>11-11 Tech aims to collect the minimum personal information necessary to communicate, qualify opportunities, deliver work and operate its public services. When the secure lead service is enabled, the project intake sends the information the visitor intentionally provides to the dedicated 11-11 Tech lead endpoint. If that service is unavailable or not configured, the website preserves a transparent email fallback instead of exposing a secret key in the browser.</p><h3>Lead and enquiry information</h3><p>Contact details, organization details, project requirements, budget range, timeline, consent, legal/procurement needs and attribution information may be processed to respond to an enquiry and manage the commercial relationship. The lead system is designed so database tables are not directly writable from the public browser.</p><h3>International work</h3><p>Production engagements must document material data locations, providers, client responsibilities and processing requirements appropriate to the service and jurisdiction.</p></Policy>
  <Policy id="terms" title="Website terms"><p>Public content is general information about 11-11 Tech, its capabilities, indicative pricing and technology portfolio. Pricing ranges are planning guidance, not binding quotations. Project descriptions distinguish active builds, prototypes, experiments and other maturity states wherever practical.</p><p>Nothing on this website creates a Statement of Work, warranty, SLA, service guarantee, employment commitment or other binding project contract. A commercial engagement exists only under the relevant accepted proposal, order form, SOW or signed agreement.</p></Policy>
  <Policy id="accessibility" title="Accessibility"><p>We design for keyboard access, visible focus, semantic structure, responsive layouts, reduced-motion preferences and readable contrast. Engagement-specific accessibility targets, standards, devices and browser support should be agreed in scope and acceptance criteria.</p></Policy>
  <Policy id="ai" title="Responsible AI"><p>AI is treated as an implementation capability rather than a single model or vendor. Projects may use commercial or open models, retrieval systems, agents, automation and connected tools according to the use case.</p><h3>Human accountability</h3><p>Consequential actions should have appropriate human control, permissions, evaluation and monitoring. Model/provider dependencies, client-data handling, retention and usage-cost assumptions should be defined before production release.</p></Policy>
  <Policy id="security" title="Security & disclosure"><p>11-11 Tech uses least-privilege thinking, environment separation, reviewable changes and evidence-led testing. Security controls are applied proportionately to the service, risk and agreed scope. Suspected vulnerabilities should be reported privately rather than publicly disclosed against an active system.</p></Policy>
  <Policy id="data" title="Cookie & data principles"><p>The public site does not require advertising cookies or cross-site marketing trackers. First-party conversion measurement is designed to use a short-lived session identifier, route/context information and campaign attribution without advertising profiles or browser fingerprinting. IP addresses may be transformed into salted hashes at the secure endpoint for abuse prevention and rate limiting rather than stored as raw analytics identifiers.</p><div className="policy-note">Legal notice: these public policies are operational information, not jurisdiction-specific legal advice. NDA, MSA, SOW, SLA, DPA, recruitment terms and other binding documents should receive appropriate review before use.</div><p><Link className="text-link" to="/trust">View the Trust & Contracting Center ↗</Link></p></Policy>
 </div></div></section>
 </>}
function Policy({id,title,children}:{id:string;title:string;children:ReactNode}){return <section className="policy-section" id={id}><h2>{title}</h2>{children}</section>}
