import { PageHero } from '../components/PageHero'
import { Link } from '../components/Link'
import { ProjectEstimator } from '../components/ProjectEstimator'
import { capabilities, pricingBands } from '../data/portfolio'

export function Pricing() {
  return <>
    <PageHero index="05" kicker="Pricing" title={<>Know the range <span className="soft">before the proposal.</span></>}>Most 11-11 Tech engagements begin between US$2,000 and US$10,000. Larger, multi-system, enterprise or ongoing programmes are scoped separately.</PageHero>
    <section className="section"><div className="wrap"><div className="pricing-band-grid">{pricingBands.map((band) => <article className="pricing-band reveal" key={band.label}><span>{band.label}</span><strong>{band.range}</strong><p>{band.detail}</p></article>)}</div></div></section>

    <section className="section alt-section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">Scope guide</div><h2>Choose a service. See the working range.</h2></div><p>This does not manufacture a quotation. It gives a client enough commercial context to decide whether a scoped conversation makes sense.</p></div><ProjectEstimator /></div></section>

    <section className="section"><div className="wrap"><div className="section-head tight reveal"><div><div className="kicker">By capability</div><h2>Indicative investment, connected to scope.</h2></div><p>These are planning ranges, not binding quotations.</p></div><div className="pricing-capability-grid">{capabilities.map((capability) => <article className="pricing-capability reveal" key={capability.id}><div><span>{capability.index} / 07</span><h3>{capability.title}</h3><p>{capability.proposition}</p></div><strong>{capability.typicalRange}</strong><div className="price-service-list">{capability.services.map((service) => <div key={service.name}><span>{service.name}</span><b>{service.price}</b></div>)}</div><Link className="btn ghost" to={`/contact?capability=${capability.id}`}>Estimate this work ↗</Link></article>)}</div></div></section>
    <section className="section alt-section"><div className="wrap"><div className="commercial-model-grid reveal"><article><span>Fixed scope</span><h3>Defined deliverable.</h3><p>Best when requirements and acceptance criteria can be agreed before implementation.</p></article><article><span>Discovery + implementation</span><h3>Pay for clarity first.</h3><p>Discovery can stand alone or become the foundation for a larger build.</p></article><article><span>Monthly partnership</span><h3>Operate and improve.</h3><p>For ongoing product, UX, AI, technical leadership or managed technology support.</p></article><article><span>Enterprise custom</span><h3>Scope the real complexity.</h3><p>Multiple systems, departments, integrations, procurement or specialized compliance are quoted separately.</p></article></div></div></section>
    <section className="section assurance-section"><div className="wrap assurance-grid"><div><div className="kicker">Commercial notes</div><h2>Transparent without pretending every project is identical.</h2></div><div className="assurance-list"><div><span>✓</span><p>Third-party cloud, model, API, software-license or media usage fees are normally separate unless explicitly included.</p></div><div><span>✓</span><p>Standard contracting and reasonable procurement support are part of the commercial process.</p></div><div><span>✓</span><p>Material client-specific compliance, certification, infrastructure or legal requirements may change scope and price.</p></div><div><span>✓</span><p>Custom pricing is always available when a predefined range does not fit the engagement.</p></div></div></div></section>
  </>
}
