import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { callCommercialAdmin, loadProjectCommercialDetail, type AdminOrganization, type AdminProject, type ProjectCommercialDetail } from '../lib/adminOps'
import { createAgreementPack, issueCommercialDocument } from '../lib/adminDocumentOps'
import { money, shortDate } from '../lib/commercial'

const blank: ProjectCommercialDetail = { plans: [], installments: [], documents: [], invoices: [], payments: [], acceptances: [] }
const documentOptions = [
  ['quotation','Quotation / Proposal'],['sow','Statement of Work'],['service_terms','Master Service Terms'],['payment_terms','Payment Terms'],['privacy','Privacy Notice'],['nda','NDA / Confidentiality'],['sla','Service Level Agreement'],['dpa','Data Processing Addendum'],['security','Security Addendum'],['ai_addendum','AI Addendum'],
] as const

export function AdminProjectConsole({ project, organization, onClose, onChanged }: { project: AdminProject; organization?: AdminOrganization; onClose: () => void; onChanged: () => Promise<void> | void }) {
  const [detail, setDetail] = useState<ProjectCommercialDetail>(blank)
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [section, setSection] = useState<'summary'|'payments'|'documents'|'manual'>('summary')
  const [plan, setPlan] = useState({ name:'50 / 50', planType:'deposit_balance', firstPercent:'50', payments:'2', allowExtra:true, minimumExtra:'100', recurringInterval:'month' })
  const [document, setDocument] = useState({ type:'quotation', title:'Quotation / Proposal', reference:'', required:true, body:'' })
  const [manual, setManual] = useState({ amount:'', method:'bank_transfer', reference:'', invoiceId:'' })

  const refresh = async () => { setLoading(true); setError(''); try { setDetail(await loadProjectCommercialDetail(project.id)) } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to load project commercial details.') } finally { setLoading(false) } }
  useEffect(() => { void refresh() }, [project.id])

  const paid = detail.payments.filter((item)=>item.status==='succeeded').reduce((sum,item)=>sum+item.amount_minor,0)
  const outstanding = Math.max(project.contract_value_minor - paid, 0)
  const requiredDocs = detail.documents.filter((doc)=>doc.required_for_acceptance && doc.status==='issued')
  const acceptedDocIds = new Set(detail.acceptances.map((item)=>item.document_id))
  const requiredAccepted = requiredDocs.length > 0 && requiredDocs.every((doc)=>acceptedDocIds.has(doc.id))
  const issuedPack = detail.documents.find((doc)=>doc.document_type==='agreement_pack' && doc.status==='issued')

  const installmentPreview = useMemo(() => buildInstallments(project.contract_value_minor, plan.planType, Number(plan.firstPercent), Number(plan.payments)), [project.contract_value_minor, plan.planType, plan.firstPercent, plan.payments])

  const createPlan = async (event:FormEvent) => {
    event.preventDefault(); setBusy('plan'); setError(''); setNotice('')
    try {
      const totalMinor = project.contract_value_minor
      const recurring = plan.planType === 'recurring'
      const installments = recurring || plan.planType === 'full' ? [] : installmentPreview.map((amountMinor,index)=>({ amountMinor, dueAt: monthDate(index) }))
      await callCommercialAdmin('create-payment-plan',{ projectId:project.id, name:plan.name, planType:plan.planType, totalMinor, installments, allowExtraPayments:plan.allowExtra && !recurring, minimumExtraPaymentMinor:plan.allowExtra && !recurring ? Math.round(Number(plan.minimumExtra||0)*100) : null, requiresAutopayAuthorization: recurring || installments.length > 1, recurringInterval:plan.recurringInterval })
      setNotice('Payment option published to the client project.')
      await refresh(); await onChanged()
    } catch(failure){setError(failure instanceof Error?failure.message:'Unable to create payment plan.')} finally{setBusy('')}
  }

  const createAndIssueDocument = async (event:FormEvent) => {
    event.preventDefault(); setBusy('document'); setError(''); setNotice('')
    try {
      if (!document.body.trim()) throw new Error('Add the approved document wording before issuing the PDF.')
      const created = await callCommercialAdmin('create-document',{ projectId:project.id, documentType:document.type, title:document.title, reference:document.reference || undefined, requiredForAcceptance:document.required, contentSnapshot:{ sections:[{ heading:document.title, body:document.body }] } }) as { document?: { id?: string } }
      const id=created.document?.id; if(!id)throw new Error('Document draft was created without an identifier.')
      await issueCommercialDocument(id)
      setNotice(`${document.title} issued as a branded, versioned PDF.`)
      setDocument((current)=>({...current,reference:'',body:''}))
      await refresh(); await onChanged()
    } catch(failure){setError(failure instanceof Error?failure.message:'Unable to issue document.')} finally{setBusy('')}
  }

  const makePack = async () => { setBusy('pack'); setError(''); setNotice(''); try { await createAgreementPack(project.id); setNotice('Agreement Pack PDF created from all currently issued project documents.'); await refresh(); await onChanged() } catch(failure){setError(failure instanceof Error?failure.message:'Unable to create Agreement Pack.')} finally{setBusy('')} }

  const recordManual = async (event:FormEvent) => { event.preventDefault(); setBusy('manual'); setError(''); setNotice(''); try { const amountMinor=Math.round(Number(manual.amount)*100); if(!amountMinor)throw new Error('Enter a payment amount.'); await callCommercialAdmin('record-manual-payment',{ projectId:project.id, invoiceId:manual.invoiceId||undefined, amountMinor, method:manual.method, externalReference:manual.reference }); setNotice('Offline payment recorded in the project ledger.'); setManual({amount:'',method:'bank_transfer',reference:'',invoiceId:''}); await refresh(); await onChanged() } catch(failure){setError(failure instanceof Error?failure.message:'Unable to record payment.')} finally{setBusy('')} }

  return <div className="project-console-backdrop" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose()}}><section className="project-console" role="dialog" aria-modal="true" aria-labelledby="project-console-title"><header><div><small>{project.reference}</small><h2 id="project-console-title">{project.title}</h2><p>{organization?.trading_name||organization?.legal_name||'Client'} · {project.service_category||'Technology engagement'}</p></div><button aria-label="Close project console" onClick={onClose}>×</button></header><div className="project-console-tabs">{(['summary','payments','documents','manual'] as const).map((value)=><button key={value} className={section===value?'active':''} onClick={()=>setSection(value)}>{value==='manual'?'Record payment':value}</button>)}</div>{error&&<div className="commercial-alert error">{error}</div>}{notice&&<div className="commercial-alert">{notice}</div>}{loading?<div className="commercial-loading">Loading project operations…</div>:<>
    {section==='summary'&&<div className="project-console-stack"><div className="project-console-metrics"><article><span>Value</span><strong>{money(project.contract_value_minor,project.currency)}</strong></article><article><span>Paid</span><strong>{money(paid,project.currency)}</strong></article><article><span>Outstanding</span><strong>{money(outstanding,project.currency)}</strong></article><article><span>Status</span><strong className="text-status">{project.status.replaceAll('_',' ')}</strong></article></div><div className="project-readiness"><h3>Commercial readiness</h3><div><span className={detail.plans.length?'ok':''}>{detail.plans.length?'✓':'○'} Payment option issued</span><span className={requiredDocs.length?'ok':''}>{requiredDocs.length?'✓':'○'} Required documents issued</span><span className={requiredAccepted?'ok':''}>{requiredAccepted?'✓':'○'} Client acceptance complete</span><span className={issuedPack?'ok':''}>{issuedPack?'✓':'○'} Agreement Pack generated</span><span className={paid>0?'ok':''}>{paid>0?'✓':'○'} First payment confirmed</span></div></div><div className="project-console-columns"><article><small>PAYMENT OPTIONS</small>{detail.plans.length?detail.plans.map((item)=><div className="console-row" key={item.id}><span><strong>{item.name}</strong><small>{item.plan_type.replaceAll('_',' ')} · {item.status}</small></span><strong>{money(item.total_minor,item.currency)}</strong></div>):<p>No payment options published.</p>}</article><article><small>RECENT DOCUMENTS</small>{detail.documents.slice(0,5).map((item)=><div className="console-row" key={item.id}><span><strong>{item.title}</strong><small>v{item.version} · {item.status}</small></span><em>{item.required_for_acceptance?'Required':'Reference'}</em></div>)}</article></div></div>}
    {section==='payments'&&<form className="console-form" onSubmit={createPlan}><div><small>PUBLISH PAYMENT OPTION</small><h3>Give the client an approved way to pay.</h3><p>Create multiple options—such as full payment, 50/50 and installments—and the client chooses one before acceptance and Checkout.</p></div><div className="field-grid"><label>Option name<input required value={plan.name} onChange={(e)=>setPlan({...plan,name:e.target.value})}/></label><label>Type<select value={plan.planType} onChange={(e)=>setPlan({...plan,planType:e.target.value,name:e.target.value==='full'?'Pay in full':e.target.value==='recurring'?'Monthly service':plan.name})}><option value="full">Pay in full</option><option value="deposit_balance">Deposit + balance</option><option value="installments">Installments</option><option value="recurring">Recurring service</option></select></label>{!['full','recurring'].includes(plan.planType)&&<><label>First payment %<select value={plan.firstPercent} onChange={(e)=>setPlan({...plan,firstPercent:e.target.value})}><option>5</option><option>10</option><option>20</option><option>25</option><option>50</option></select></label><label>Total payments<input type="number" min="2" max="24" value={plan.payments} onChange={(e)=>setPlan({...plan,payments:e.target.value})}/></label></>}{plan.planType==='recurring'&&<label>Billing interval<select value={plan.recurringInterval} onChange={(e)=>setPlan({...plan,recurringInterval:e.target.value})}><option value="month">Monthly</option><option value="quarter">Quarterly</option><option value="year">Yearly</option></select></label>}</div>{!['full','recurring'].includes(plan.planType)&&<div className="plan-preview"><strong>Schedule preview</strong>{installmentPreview.map((amount,index)=><span key={index}>#{index+1} · {money(amount,project.currency)} · {index===0?'due at acceptance':shortDate(monthDate(index))}</span>)}</div>}<label className="check-line"><input type="checkbox" checked={plan.allowExtra} onChange={(e)=>setPlan({...plan,allowExtra:e.target.checked})} disabled={plan.planType==='recurring'}/><span>Allow additional balance payments</span></label>{plan.allowExtra&&plan.planType!=='recurring'&&<label>Minimum extra payment<input type="number" min="1" step="1" value={plan.minimumExtra} onChange={(e)=>setPlan({...plan,minimumExtra:e.target.value})}/></label>}<button className="btn primary" disabled={busy==='plan'}>{busy==='plan'?'Publishing…':'Publish payment option ↗'}</button></form>}
    {section==='documents'&&<div className="project-console-stack"><form className="console-form" onSubmit={createAndIssueDocument}><div><small>ISSUE CONTROLLED PDF</small><h3>Create a versioned project document.</h3><p>Paste only approved wording. Issued PDFs are stored privately, hashed and later tied to client acceptance evidence.</p></div><div className="field-grid"><label>Document type<select value={document.type} onChange={(e)=>{const found=documentOptions.find(([id])=>id===e.target.value);setDocument({...document,type:e.target.value,title:found?.[1]||document.title})}}>{documentOptions.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Title<input required value={document.title} onChange={(e)=>setDocument({...document,title:e.target.value})}/></label><label>Reference<input value={document.reference} onChange={(e)=>setDocument({...document,reference:e.target.value})} placeholder="11T-Q-2026-0042"/></label><label className="check-line"><input type="checkbox" checked={document.required} onChange={(e)=>setDocument({...document,required:e.target.checked})}/><span>Required before first payment</span></label></div><label>Approved content<textarea required rows={12} value={document.body} onChange={(e)=>setDocument({...document,body:e.target.value})} placeholder="Approved project-specific wording…"/></label><button className="btn primary" disabled={busy==='document'}>{busy==='document'?'Rendering PDF…':'Create & issue PDF ↗'}</button></form><div className="document-pack-control"><div><small>AGREEMENT PACKAGE</small><h3>Combine the issued documents.</h3><p>Creates one client-friendly PDF while preserving every individual source document and hash.</p></div><button className="btn secondary" disabled={busy==='pack'||!detail.documents.some((doc)=>doc.status==='issued'&&doc.document_type!=='agreement_pack')} onClick={()=>void makePack()}>{busy==='pack'?'Building pack…':'Generate Agreement Pack PDF'}</button></div><div className="console-doc-register">{detail.documents.map((item)=><div key={item.id}><span><strong>{item.title}</strong><small>{item.reference||item.document_type} · v{item.version} · {item.issued_at?shortDate(item.issued_at):'Draft'}</small></span><em className={`status-pill ${item.status}`}>{item.status}</em></div>)}</div></div>}
    {section==='manual'&&<form className="console-form" onSubmit={recordManual}><div><small>OFFLINE / EXTERNAL PAYMENT</small><h3>Record money received outside Stripe.</h3><p>Use this for an approved bank transfer, cash, mobile money, PayPal or other external payment. It enters the same project ledger.</p></div><div className="field-grid"><label>Amount ({project.currency})<input required type="number" min="0.01" step="0.01" value={manual.amount} onChange={(e)=>setManual({...manual,amount:e.target.value})}/></label><label>Method<select value={manual.method} onChange={(e)=>setManual({...manual,method:e.target.value})}><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="mobile_money">Mobile money</option><option value="paypal">PayPal</option><option value="other">Other</option></select></label><label>External reference<input value={manual.reference} onChange={(e)=>setManual({...manual,reference:e.target.value})}/></label><label>Apply to invoice<select value={manual.invoiceId} onChange={(e)=>setManual({...manual,invoiceId:e.target.value})}><option value="">Project balance / no invoice</option>{detail.invoices.filter((item)=>!['paid','void','uncollectible'].includes(item.status)).map((item)=><option key={item.id} value={item.id}>{item.reference} · {money(item.amount_due_minor-item.amount_paid_minor,item.currency)} outstanding</option>)}</select></label></div><button className="btn primary" disabled={busy==='manual'}>{busy==='manual'?'Recording…':'Record payment ↗'}</button></form>}
  </>}</section></div>
}

function buildInstallments(total:number,type:string,firstPercent:number,count:number){
  if(type==='full')return [total]
  const safeCount=Math.max(2,Math.min(24,Number.isFinite(count)?count:2))
  const first=Math.max(1,Math.min(total-1,Math.round(total*Math.max(1,Math.min(99,firstPercent))/100)))
  const remaining=total-first;const base=Math.floor(remaining/(safeCount-1));const amounts=[first]
  for(let i=1;i<safeCount;i++)amounts.push(base+(i===safeCount-1?remaining-base*(safeCount-1):0))
  return amounts
}
function monthDate(index:number){const d=new Date();d.setHours(12,0,0,0);d.setMonth(d.getMonth()+index);return d.toISOString()}
