import type { CapabilityId } from './portfolio'

export type ProjectTaxonomy = {
  capabilities: CapabilityId[]
  solutions: string[]
  industries: string[]
  outcomes: string[]
  transferability: string[]
}

export const projectTaxonomy: Record<string, ProjectTaxonomy> = {
  carup: { capabilities: ['ui-ux','enterprise','software-data-cloud','trust'], solutions: ['Marketplace engineering','Asset identity','Verification','Dealer operations'], industries: ['Automotive & Mobility','Commerce & Marketplaces'], outcomes: ['Trust','Operational visibility','Connected transactions'], transferability: ['Dealer networks','Insurance workflows','Asset registries','Regulated marketplaces'] },
  'church-os': { capabilities: ['ui-ux','enterprise','ai','transformation','trust'], solutions: ['CRM / relationship systems','Membership','Case management','AI context'], industries: ['Nonprofits, NGOs & Membership','Institutional & Regulated Operations'], outcomes: ['One source of truth','Better member journeys','Governed operations'], transferability: ['Membership organizations','Nonprofits','Associations','Multi-tenant operations'] },
  sessions: { capabilities: ['ui-ux','enterprise','software-data-cloud'], solutions: ['Booking platform','Provider portal','Marketplace operations','Membership'], industries: ['Commerce & Marketplaces'], outcomes: ['Booking integrity','Provider operations','Discovery'], transferability: ['Salons','Clinics','Facilities','Service marketplaces'] },
  healthtimes: { capabilities: ['ui-ux','ai','software-data-cloud','transformation','trust'], solutions: ['Editorial modernization','Subscriber systems','Newsroom workflow','PWA'], industries: ['Media & Publishing'], outcomes: ['Modern reader experience','Governed publishing','Operational modernization'], transferability: ['Publishers','Associations','Premium content businesses'] },
  'morning-pulse': { capabilities: ['ui-ux','ai','software-data-cloud','transformation'], solutions: ['AI-assisted newsroom','Information intelligence','Editorial workflow'], industries: ['Media & Publishing'], outcomes: ['Faster information workflows','Editorial intelligence'], transferability: ['Newsrooms','Research teams','Knowledge operations'] },
  wewed: { capabilities: ['ui-ux','enterprise','software-data-cloud'], solutions: ['Event platform','Vendor marketplace','Guest operations'], industries: ['Commerce & Marketplaces'], outcomes: ['Connected event journey','Vendor coordination'], transferability: ['Events','Hospitality','Multi-party planning'] },
  direkt: { capabilities: ['ui-ux','enterprise','software-data-cloud','trust'], solutions: ['Verification-led marketplace','Provider identity','Evidence workflows'], industries: ['Institutional & Regulated Operations','Commerce & Marketplaces'], outcomes: ['Verified discovery','Evidence-led trust'], transferability: ['Local services','Contractor networks','Provider marketplaces'] },
  'alt-game-center': { capabilities: ['ui-ux','software-data-cloud','transformation'], solutions: ['Interactive learning','Moderator UX','Gamification'], industries: ['Education & Training'], outcomes: ['Faster classroom interaction','Reusable teaching workflows'], transferability: ['Training','Workshops','Interactive presentations'] },
  'count-with-dad': { capabilities: ['ui-ux','software-data-cloud'], solutions: ['Learning UX','Gamified practice'], industries: ['Education & Training'], outcomes: ['Engagement','Family learning'], transferability: ['Early learning','Family education'] },
  'kotsu-sensei': { capabilities: ['ui-ux','software-data-cloud'], solutions: ['Practice system','Learning simulation'], industries: ['Education & Training'], outcomes: ['Repeatable practice','Decision feedback'], transferability: ['Training','Certification preparation'] },
  'phonics-kids-pro': { capabilities: ['ui-ux','software-data-cloud'], solutions: ['Multimedia learning','Practice workflows'], industries: ['Education & Training'], outcomes: ['Structured practice','Child-friendly interaction'], transferability: ['Language learning','Early education'] },
  'pay-pass': { capabilities: ['ui-ux','software-data-cloud','trust'], solutions: ['Payment workflow','Retail UX','Authorization'], industries: ['Commerce & Marketplaces'], outcomes: ['Faster checkout','Clear transaction state'], transferability: ['Retail','Events','Membership payments'] },
  'paid-refer': { capabilities: ['enterprise','talent','software-data-cloud'], solutions: ['Referral platform','Attribution','Recruitment technology'], industries: ['HR & Recruitment','Commerce & Marketplaces'], outcomes: ['Trackable referrals','Clear incentives'], transferability: ['Recruitment','Affiliate programmes','Partner referrals'] },
  schoolrun: { capabilities: ['ui-ux','enterprise','software-data-cloud','trust'], solutions: ['Mobility operations','Routing','Guardian workflows'], industries: ['Automotive & Mobility','Education & Training'], outcomes: ['Operational visibility','Safer coordination'], transferability: ['Transport','Field operations','Fleet coordination'] },
  tengasell: { capabilities: ['ui-ux','enterprise','software-data-cloud'], solutions: ['Marketplace','Seller operations'], industries: ['Commerce & Marketplaces'], outcomes: ['Digital selling','Localized commerce'], transferability: ['Retail marketplaces','Seller platforms'] },
  billify: { capabilities: ['ai','enterprise','software-data-cloud'], solutions: ['Document automation','Billing workflow'], industries: ['Commerce & Marketplaces'], outcomes: ['Less administration','Consistent documents'], transferability: ['Invoices','Quotations','Operational documents'] },
  'reverse-verify': { capabilities: ['ai','software-data-cloud','trust'], solutions: ['Verification','Evidence lookup','Trust signals'], industries: ['Institutional & Regulated Operations'], outcomes: ['Better due diligence','Visible evidence'], transferability: ['Onboarding','Supplier checks','Asset verification'] },
  jd2cv: { capabilities: ['ai','talent','ui-ux'], solutions: ['Recruitment intelligence','Document AI','Candidate tooling'], industries: ['HR & Recruitment'], outcomes: ['Better role alignment','Faster application preparation'], transferability: ['Recruiter tools','Talent intelligence','Career platforms'] },
  characterforge: { capabilities: ['ai','ui-ux'], solutions: ['Generative media','Multimodal workflow'], industries: ['Media & Publishing'], outcomes: ['Repeatable creative generation'], transferability: ['Brand assets','Creative tooling','Content production'] },
  growhome: { capabilities: ['ui-ux','enterprise','software-data-cloud'], solutions: ['Property discovery','Decision support','Lifecycle platform'], industries: ['Property Technology'], outcomes: ['Clearer property decisions'], transferability: ['Real estate','Property operations'] },
  rentguarantee: { capabilities: ['enterprise','software-data-cloud','trust'], solutions: ['Tenancy workflow','Risk and guarantee','Document process'], industries: ['Property Technology','Institutional & Regulated Operations'], outcomes: ['Clearer tenancy decisions','Controlled risk workflow'], transferability: ['Leasing','Underwriting-style workflows','Applications'] },
  'agentic-ai': { capabilities: ['ai','software-data-cloud','trust'], solutions: ['AI agents','Orchestration','Tool use','Evaluation'], industries: ['Cross-industry'], outcomes: ['Multi-step automation','AI product experimentation'], transferability: ['Operations','Research','Customer service','Internal copilots'] },
}
