export type Project = {
  name: string
  slug: string
  category: string
  status: string
  region: string
  description: string
  featured?: boolean
  repository?: string
  focus?: string[]
}

export const projects: Project[] = [
  { name: 'CarUp', slug: 'carup', category: 'Mobility', status: 'Active build', region: 'Zimbabwe / diaspora', featured: true, repository: 'https://github.com/kudzimusar/carup', description: 'Automotive marketplace and trust network connecting listings with vehicle identity, evidence, seller workflows and intelligence.', focus: ['Vehicle Digital Passport and evidence-led trust', 'Seller, buyer, garage and marketplace lifecycle', 'Zimbabwe and diaspora market context'] },
  { name: 'Church OS', slug: 'church-os', category: 'Community', status: 'Advanced build', region: 'Global', featured: true, description: 'A multi-surface operating system for church operations, member journeys, communications, care, governance and shared AI context.', focus: ['Member journey and pastoral-care operations', 'Tenant, privacy and privileged-security boundaries', 'Shared AI context with operational governance'] },
  { name: 'Sessions', slug: 'sessions', category: 'Commerce', status: 'Active build', region: 'Zimbabwe', featured: true, repository: 'https://github.com/kudzimusar/sessions-music', description: 'Mobile-first rehearsal infrastructure marketplace with studio discovery, provider operations, booking integrity and marketplace governance.', focus: ['Real studio registry and provider ownership', 'Room availability, booking integrity and settlement controls', 'Customer, provider and corporate surfaces on one product domain'] },
  { name: 'HealthTimes 2.1', slug: 'healthtimes', category: 'Media', status: 'Client review', region: 'Zimbabwe', featured: true, repository: 'https://github.com/kudzimusar/htp-zw', description: 'Modernized premium health publication with newsroom workflows, mobile UX, subscriber systems, advertising and HealthTimes Intelligence.', focus: ['Premium reader and publication experience', 'Role-governed newsroom and advertising operations', 'PWA/mobile packaging and client-review certification'] },
  { name: 'Morning Pulse', slug: 'morning-pulse', category: 'Media', status: 'Product build', region: 'Zimbabwe / diaspora', featured: true, repository: 'https://github.com/kudzimusar/morning-pulse', description: 'AI-assisted news platform combining an interactive news experience with a full digital newsroom and editorial workflow.', focus: ['Interactive news discovery and AI-assisted Q&A', 'Editorial workflow and stakeholder operations', 'Zimbabwe-first media product model'] },
  { name: 'wewed', slug: 'wewed', category: 'Commerce', status: 'Product build', region: 'Global', featured: true, repository: 'https://github.com/kudzimusar/wewed', description: 'Wedding experience and planning platform spanning RSVP, guest journeys, media, vendor discovery, planner tools, live moments and post-event memory.', focus: ['Wedding lifecycle before and after the event', 'RSVP, planning, vendors, media and live participation', 'Couple-facing administration and product theming'] },
  { name: 'DIREKT', slug: 'direkt', category: 'Trust', status: 'Pilot readiness', region: 'Zambia', featured: true, repository: 'https://github.com/kudzimusar/direkt', description: 'Verification-led local services marketplace for trusted discovery of plumbers, electricians, mechanics and other providers.', focus: ['Evidence-backed verification rather than generic badges', 'Android-first customer/provider experience with web/PWA parity', 'Controlled pilot and operations readiness'] },
  { name: 'ALT Game Center', slug: 'alt-game-center', category: 'Education', status: 'In use / evolving', region: 'Japan', featured: true, repository: 'https://github.com/kudzimusar/alt-game-center', description: 'Moderator-first classroom games for ALTs in Japan, built around fast keyboard control, visible scoring, hints and reusable grammar activities.', focus: ['Classroom-first keyboard moderation', 'Reusable JHS activities across grades and grammar targets', 'Fast visual interaction for projector-based teaching'] },
  { name: 'Count With Dad', slug: 'count-with-dad', category: 'Education', status: 'Prototype', region: 'Japan / global', repository: 'https://github.com/kudzimusar/count-with-dad', description: 'A family-oriented counting and early-learning product experiment focused on playful parent-child interaction.' },
  { name: 'Kotsu Sensei Practice', slug: 'kotsu-sensei', category: 'Education', status: 'Prototype', region: 'Japan', repository: 'https://github.com/kudzimusar/kotsu-sensei-practice', description: 'Interactive driving-test study and practice experience designed around Japanese road knowledge and repeatable learning.' },
  { name: 'Phonics Kids Pro', slug: 'phonics-kids-pro', category: 'Education', status: 'Prototype', region: 'Japan / global', repository: 'https://github.com/kudzimusar/phonics_kids_pro', description: 'Phonics and early English learning product exploring structured sound, reading and child-friendly practice flows.' },
  { name: 'Pay Pass', slug: 'pay-pass', category: 'Commerce', status: 'Prototype', region: 'Global', repository: 'https://github.com/kudzimusar/pay-pass-scan-and-go', description: 'Scan-and-go commerce concept exploring fast checkout, payment flow and friction reduction in retail experiences.' },
  { name: 'Paid Refer', slug: 'paid-refer', category: 'Commerce', status: 'Prototype', region: 'Global', repository: 'https://github.com/kudzimusar/Paid-Refer', description: 'Referral-product experiment focused on trackable introductions, incentives and platform-mediated referral journeys.' },
  { name: 'SchoolRun', slug: 'schoolrun', category: 'Mobility', status: 'Prototype', region: 'Japan / global', repository: 'https://github.com/kudzimusar/schoolrun-bus-app', description: 'School transport coordination concept exploring route, family and operations experiences around the daily school run.' },
  { name: 'TengaSell', slug: 'tengasell', category: 'Commerce', status: 'Earlier build', region: 'Africa', description: 'Earlier marketplace and commerce work exploring digital buying, selling and localized online retail experiences.' },
  { name: 'Billify Generator', slug: 'billify', category: 'Tools', status: 'Prototype', region: 'Global', description: 'Lightweight billing and document-generation utility for turning structured inputs into usable customer-facing invoices.' },
  { name: 'Reverse Verification Tool', slug: 'reverse-verify', category: 'Trust', status: 'Prototype', region: 'Global', repository: 'https://github.com/kudzimusar/reverse-verification-tool', description: 'Verification utility exploring evidence-first checks, reverse lookup patterns and clearer trust signals.' },
  { name: 'JD2CV', slug: 'jd2cv', category: 'AI', status: 'Prototype', region: 'Global', repository: 'https://github.com/kudzimusar/jd2cv-maker-ai', description: 'AI-assisted tool for translating job descriptions into more targeted CV structure and application preparation.' },
  { name: 'CharacterForge', slug: 'characterforge', category: 'AI', status: 'Experiment', region: 'Global', description: 'Creative image and character-generation experiment exploring repeatable visual identity workflows.' },
  { name: 'GrowHome Japan', slug: 'growhome', category: 'Property', status: 'Blueprint', region: 'Japan', description: 'Property and housing product blueprint focused on simplifying home discovery and decision support in Japan.' },
  { name: 'RentGuarantee', slug: 'rentguarantee', category: 'Property', status: 'Prototype', region: 'Japan', repository: 'https://github.com/kudzimusar/rentguarantee-haven-56924', description: 'Rental-guarantee product exploration around clearer renter, guarantor and property workflows.' },
  { name: 'Agentic AI Lab', slug: 'agentic-ai', category: 'AI', status: 'Experiment', region: 'Global', description: 'Internal experimentation with agentic product workflows, orchestration patterns and AI-assisted software delivery.' },
]

export const categories = ['All', ...Array.from(new Set(projects.map((project) => project.category)))]
