import { StyleSheet, Text, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { Screen } from '../../src/components/Screen'
import { AppHeader } from '../../src/components/AppHeader'
import { ActionButton } from '../../src/components/ActionButton'
import { CinematicHero, Disclosure, HorizontalMediaRail, MediaCard, Pill } from '../../src/components/Editorial'
import { getCapability } from '../../../shared/portfolio'
import { capabilityMedia, media } from '../../../shared/media'
import { projects } from '../../src/data/projects'
import { useTheme } from '../../src/theme/ThemeProvider'
import { spacing, type } from '../../src/theme/tokens'

export default function CapabilityDetail(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const{theme}=useTheme();const cap=getCapability(id||'');if(!cap)return <Screen><AppHeader back title="Capability"/><Text style={{color:theme.text}}>Capability not found.</Text></Screen>;const proof=cap.proof.map(slug=>projects.find(p=>p.slug===slug)).filter(Boolean);return <Screen><AppHeader back title={cap.shortTitle}/><CinematicHero image={capabilityMedia[cap.id]} eyebrow={`${cap.index} · ${cap.shortTitle}`} title={cap.proposition} body={cap.problem}/>
<View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>TRANSFORMATION</Text><Text style={[styles.heading,{color:theme.text}]}>{cap.transformation}</Text><View style={styles.pills}>{cap.outcomes.map(x=><Pill key={x}>{x}</Pill>)}</View></View>
<View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>SYSTEM THINKING</Text>{cap.systemThinking.map((x,i)=><View key={x} style={[styles.numberRow,{borderColor:theme.rule}]}><Text style={[styles.number,{color:theme.accent}]}>{String(i+1).padStart(2,'0')}</Text><Text style={[styles.rowText,{color:theme.text}]}>{x}</Text></View>)}</View>
<View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>WHAT WE IMPLEMENT</Text>{cap.services.map(service=><Disclosure key={service.name} title={`${service.name} · ${service.price}`} summary={service.summary}><Text style={[styles.body,{color:theme.muted}]}>{service.summary}</Text><View style={styles.pills}>{service.examples.map(x=><Pill key={x}>{x}</Pill>)}</View></Disclosure>)}</View>
<View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>DELIVERY & ASSURANCE</Text>{cap.assurance.map(x=><Text key={x} style={[styles.body,{color:theme.muted}]}>✓ {x}</Text>)}<View style={[styles.price,{backgroundColor:theme.surface,borderColor:theme.rule}]}><Text style={[styles.priceLabel,{color:theme.muted}]}>TYPICAL RANGE</Text><Text style={[styles.priceValue,{color:theme.text}]}>{cap.typicalRange}</Text><Text style={[styles.body,{color:theme.muted}]}>Starting at {cap.startingAt}. Final scope depends on complexity, integrations, data, timeline, procurement and legal/compliance requirements.</Text></View></View>
{proof.length?<View style={styles.section}><Text style={[styles.kicker,{color:theme.accent}]}>TRANSFERABLE PROOF</Text><HorizontalMediaRail>{proof.slice(0,6).map(p=><MediaCard key={p!.slug} image={media.systems} label={`${p!.category} · ${p!.status}`} title={p!.name} detail={p!.description} onPress={()=>router.push(`/project/${p!.slug}`)}/>)}</HorizontalMediaRail></View>:null}
<View style={styles.section}><ActionButton label="Start with this capability" detail={cap.shortTitle} onPress={()=>router.push({pathname:'/start',params:{capability:cap.id}})}/><ActionButton label="See pricing" variant="outline" onPress={()=>router.push('/pricing')}/></View></Screen>}
const styles=StyleSheet.create({section:{gap:14,marginTop:44},kicker:{fontFamily:type.mono,fontSize:9,letterSpacing:1.3},heading:{fontFamily:type.display,fontSize:29,lineHeight:31,textTransform:'uppercase'},body:{fontFamily:type.body,fontSize:15,lineHeight:22},pills:{flexDirection:'row',flexWrap:'wrap',gap:8},numberRow:{minHeight:58,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center',gap:12},number:{fontFamily:type.mono,fontSize:9,width:28},rowText:{fontFamily:type.body,fontSize:15,fontWeight:'600',flex:1},price:{padding:18,borderWidth:StyleSheet.hairlineWidth,gap:8},priceLabel:{fontFamily:type.mono,fontSize:9,letterSpacing:1.2},priceValue:{fontFamily:type.display,fontSize:34}})
